
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import TopNav from '@/app/component/topnav'
import Themer from '@/theme/themer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Kevin\'s Basic Webapp',
  description: 'Generated by create next app, then modified to do what I want',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Themer> 
        <body className={inter.className}>
          <TopNav />
          {children}
        </body>
      </Themer>
    </html>
  )
}
